dataRoot: tickLogs
subscriptions:
    - {symbol: VXX, currency: USD, exchange: SMART, secType: STK}
    - {symbol: SPY, currency: USD, exchange: SMART, secType: STK}
#    - {symbol: VIX, currency: USD, exchange: CBOE, secType: IND}
#    - {symbol: VXV,  currency: USD, exchange: CBOE, secType: IND}
  
